# numpy

In [1]:
import numpy as  np

### 创建多维数组对象
#### ndarray
```python
import numpy as  np
np.array('array_like')
```

##### 数组与列表区别
- 数组对象内的元素类型必须相同
- 数组大小不可修改
##### ndarray数据了性
- 布尔型 bool_
- 整型 int_ int8 int16 int32 int64
- 无符号整形 uint8 uint16 uint32 uint64
- 浮点型 float_ float16 float32 float64
- 复数型 complex_ complex64 complex128

In [2]:
import random
a = np.array([random.uniform(1,100) for i in range(100)])
b = np.array([random.randint(100,200) for i in range(100)])

In [3]:
# 数组元素同时运算
a * 2

array([ 96.76575749, 199.64729493,  48.43592994, 117.88731141,
       182.81325286, 167.93475767,  71.75063771,  37.66871008,
       103.54114344,  58.2387781 ,  12.54098832,  48.22776698,
       116.5450972 ,  97.43404182,  30.54255337, 100.94779313,
        87.22552035,  20.87250129,  67.04133382,  67.93735427,
        13.08890353,  71.99056839,  15.19308908, 137.88713631,
        26.00944315, 107.85753805,   6.15292205,  57.4176331 ,
        57.17423834, 140.59483331,  74.94359652,  93.8729705 ,
       192.5793025 ,  88.50234991,  87.1358844 ,  70.02555608,
       191.44758068,  77.94768512, 179.12644267, 192.96645607,
        23.2270357 , 195.76447556, 179.98470393, 129.44316539,
        76.33153977, 109.78238803,  16.5594733 ,  29.89993512,
         6.12773452, 155.98525008, 142.02993556,  95.45145628,
        82.06534055,   2.32798538, 117.06967328, 118.44721814,
       120.15331966, 189.34163146,  45.51697669,  93.90271852,
       112.50264715, 126.27302705, 147.98881085,  89.83

In [4]:
# 两个数组运算
a * b

array([ 9531.42711323, 11879.01404813,  3099.89951593,  8900.49201147,
       10603.16866579, 12427.17206784,  4771.41740739,  3465.52132736,
        7144.3388972 ,  5008.53491675,  1254.09883213,  3158.91873735,
        6060.34505446,  7599.85526168,  1740.92554187,  6965.39772611,
        7806.68407124,  1294.0950797 ,  6100.7613773 ,  4517.83405877,
        1132.19015526,  6083.20302932,   843.21644366,  6894.35681527,
        1976.71767973,  9815.0359623 ,   556.83944546,  3244.09627002,
        3144.58310893,  9982.23316528,  6295.26210758,  7791.45655152,
       17043.26827122,  4734.87572001,  7755.09371176,  6477.36393728,
       18091.79637391,  5456.33795808, 11732.78199511, 10130.73894367,
        2113.66024825, 17423.03832503, 11878.99045918, 10420.1748135 ,
        6679.00972953, 10209.76208653,  1374.43628415,  1689.34633436,
         392.17500935,  9515.10025494,  7669.61652035,  7158.85922119,
        5088.05111428,   199.04275029,  7668.06360014, 10541.80241475,
      

In [5]:
# 两个数组同时运算并求和
(a * b).sum()

717407.3972718231

In [6]:
# 数组类型
a.dtype

dtype('float64')

In [7]:
# 数组元素个数
a.size

100

In [8]:
# 多维数组
a = np.array([[1,2,3],[4,5,6]])

In [9]:
# 多维数组类型
a.dtype

dtype('int64')

In [10]:
# 多维数组元素个数
a.size

6

In [11]:
# 多维数组纬度个数(行数，列数)
a.shape

(2, 3)

In [12]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [13]:
# 数组转置[[1,2,3],[4,5,6]]转换成[[1.4],[2,5],[3,6]]
a.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [14]:
# 返回数组纬度
a.ndim

2

## 创建数组

### 创建全零数组

In [15]:
# 创建浮点数数组
n = np.zeros(10)
n.dtype

dtype('float64')

In [16]:
# 创建整型数组
n = np.zeros(10, dtype='int_')
n.dtype

dtype('int64')

### 创建全一数组

In [17]:
n = np.ones(10)
n = np.ones(10,dtype='int_')
n.dtype
n

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### 创建空数组（随机值）

In [18]:
n = np.empty(100)
n

array([48.38287875, 99.82364746, 24.21796497, 58.94365571, 91.40662643,
       83.96737884, 35.87531885, 18.83435504, 51.77057172, 29.11938905,
        6.27049416, 24.11388349, 58.2725486 , 48.71702091, 15.27127668,
       50.47389657, 43.61276017, 10.43625064, 33.52066691, 33.96867713,
        6.54445176, 35.9952842 ,  7.59654454, 68.94356815, 13.00472158,
       53.92876902,  3.07646102, 28.70881655, 28.58711917, 70.29741666,
       37.47179826, 46.93648525, 96.28965125, 44.25117495, 43.5679422 ,
       35.01277804, 95.72379034, 38.97384256, 89.56322134, 96.48322803,
       11.61351785, 97.88223778, 89.99235196, 64.72158269, 38.16576988,
       54.89119401,  8.27973665, 14.94996756,  3.06386726, 77.99262504,
       71.01496778, 47.72572814, 41.03267028,  1.16399269, 58.53483664,
       59.22360907, 60.07665983, 94.67081573, 22.75848835, 46.95135926,
       56.25132358, 63.13651352, 73.99440542, 44.91588287,  1.6334146 ,
       34.15194768, 87.76544677, 46.9266696 , 56.31480865, 90.39

### 创建数组类似于range

In [19]:
n = np.arange(0,100,2) # 起始值，结束值-1，步长(可以是小数)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

### 等差数列数组

In [20]:
n = np.linspace(0,100,1000) # 起始值 结束值 拆分份数
n

array([  0.        ,   0.1001001 ,   0.2002002 ,   0.3003003 ,
         0.4004004 ,   0.5005005 ,   0.6006006 ,   0.7007007 ,
         0.8008008 ,   0.9009009 ,   1.001001  ,   1.1011011 ,
         1.2012012 ,   1.3013013 ,   1.4014014 ,   1.5015015 ,
         1.6016016 ,   1.7017017 ,   1.8018018 ,   1.9019019 ,
         2.002002  ,   2.1021021 ,   2.2022022 ,   2.3023023 ,
         2.4024024 ,   2.5025025 ,   2.6026026 ,   2.7027027 ,
         2.8028028 ,   2.9029029 ,   3.003003  ,   3.1031031 ,
         3.2032032 ,   3.3033033 ,   3.4034034 ,   3.5035035 ,
         3.6036036 ,   3.7037037 ,   3.8038038 ,   3.9039039 ,
         4.004004  ,   4.1041041 ,   4.2042042 ,   4.3043043 ,
         4.4044044 ,   4.5045045 ,   4.6046046 ,   4.7047047 ,
         4.8048048 ,   4.9049049 ,   5.00500501,   5.10510511,
         5.20520521,   5.30530531,   5.40540541,   5.50550551,
         5.60560561,   5.70570571,   5.80580581,   5.90590591,
         6.00600601,   6.10610611,   6.20620621,   6.30

### 线性代数，单位矩阵数组

In [21]:
n = np.eye(10) # 二维数组开始和最后的值相等
n

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

### 批量运算

> 数组和标量之间的运算
> a+3 a*3 1//a a**0.5 a>5
> 同样大小数组之间的运算
> a+b a/b a**b a%b a==b

标量：一个定义好的数字
向量：一个定义好的数组

In [22]:
# 数组和标量之间的运算
# a+3 a*3 1//a a**0.5 a>5
a = np.arange(10)
a + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [23]:
# 同样大小数组之间的运算
# a+b a/b a**b a%b a==b
a = np.arange(1,10)
b = np.arange(7,16)
a < b

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

#### 生成二维数组

In [24]:
n = np.arange(15).reshape((3,5))
n

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

#### 索引

In [25]:
n[1][2]
# 第二种写法
n[1,2]

7

#### 切片

In [26]:
n = np.arange(15)

In [27]:
n[0:4]

array([0, 1, 2, 3])

##### 数组与列表 切片中的不同

> 数组是内存地址引用，列表是映射

In [28]:
a = [0,1,2,3,4,5,6,7,8,9]
b = np.arange(10)
c = a[0:4]
d= b[0:4]
c[0] = 20
d[0] = 20

In [29]:
a # python 列表 切片 数据映射 会生成新的列表，原列表值不会改变

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [30]:
b
# 数组 切片 地址引用 不会生成新的列表 在原有列表做地址引用 切片赋值会改变原数组值
# 如果想达到列表的效果可以在切片赋值前将切片的数据b.copy() 深拷贝生成一个新数组

array([20,  1,  2,  3,  4,  5,  6,  7,  8,  9])

#### 多维数组切片

In [31]:
# 数据准备
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [32]:
# 多维数组切片  a[行:行-1,列:列-1]
a[1:,2:4]

array([[ 7,  8],
       [12, 13]])

### 布尔型索引

In [33]:
# 给一个数组选出元素大于5的数
a = [random.randint(0,10) for i in range(10)]
list(filter(lambda x:x>5,a))

[6, 7, 7, 10, 10, 6, 7]

In [34]:
# numpy 实现方法
a = np.array(a)
# 返回所有布尔索引为true的值
a[a>5]

array([ 6,  7,  7, 10, 10,  6,  7])

In [35]:
# 与 或
a[(a>5)&(a%2==0)]

array([ 6, 10, 10,  6])

In [36]:
a[(a>5) | (a%2==0)]

array([ 4,  6,  7,  7, 10, 10,  6,  7])

### 花式索引(没懂)

In [37]:
# 选出1，3，4，6，7个数组，组成新的二维数组

In [38]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [39]:
a[[1,3,4,6,12]]

array([ 1,  3,  4,  6, 12])

## 通用函数
> 能同时对数组中所有元素进行运算的函数
一元函数：abs,sqrt,exp,log,ceil,floor,rint,trunc,modf,isnan,isinf,cos,sin,tan
二元函数：add,substract,multiply,divide,power,mod,maximum,mininum

### 一元函数

In [40]:
# 绝对值
a = np.arange(-5,5)
np.abs(a)

array([5, 4, 3, 2, 1, 0, 1, 2, 3, 4])

In [41]:
# 开方

In [42]:
a = np.arange(5,10)
np.sqrt(a)

array([2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [43]:
# 按方向取整

In [44]:
a = np.arange(-5.5, 5.5)
a

array([-5.5, -4.5, -3.5, -2.5, -1.5, -0.5,  0.5,  1.5,  2.5,  3.5,  4.5])

In [45]:
# 向下取整
np.floor(a)

array([-6., -5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.])

In [46]:
# 向下取整
np.ceil(a)

array([-5., -4., -3., -2., -1., -0.,  1.,  2.,  3.,  4.,  5.])

In [47]:
# 四舍六入五成双
np.round(a)

array([-6., -4., -4., -2., -2., -0.,  0.,  2.,  2.,  4.,  4.])

In [48]:
# 向零取整
np.trunc(a)

array([-5., -4., -3., -2., -1., -0.,  0.,  1.,  2.,  3.,  4.])

In [49]:
# 把小数分开
np.modf(a)

(array([-0.5, -0.5, -0.5, -0.5, -0.5, -0.5,  0.5,  0.5,  0.5,  0.5,  0.5]),
 array([-5., -4., -3., -2., -1., -0.,  0.,  1.,  2.,  3.,  4.]))

### 浮点数特殊值
> nan：不等于任何浮点数（nan ！= nan）(不是一个数字)   特性：nan ！= nan
inf：比任何浮点数都大（最大的数字）   特性:inf == inf
np创建特殊值：np.nan   np.inf
在数据分析中，nan常被用作数据缺失值

In [50]:
#
a = np.arange(0, 5)
5/a

/var/folders/hr/ppfykdg56ks4mjvczmbjkv1w0000gn/T/ipykernel_72453/924957107.py:3: RuntimeWarning: divide by zero encountered in true_divide
  5/a


array([       inf, 5.        , 2.5       , 1.66666667, 1.25      ])

In [51]:
a = np.arange(-5.5,5.5)
np.sqrt(a)

/var/folders/hr/ppfykdg56ks4mjvczmbjkv1w0000gn/T/ipykernel_72453/2623976932.py:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(a)


array([       nan,        nan,        nan,        nan,        nan,
              nan, 0.70710678, 1.22474487, 1.58113883, 1.87082869,
       2.12132034])

In [52]:
# 判断数组里是否有nan值
np.isnan(np.sqrt(a))

/var/folders/hr/ppfykdg56ks4mjvczmbjkv1w0000gn/T/ipykernel_72453/1843299488.py:2: RuntimeWarning: invalid value encountered in sqrt
  np.isnan(np.sqrt(a))


array([ True,  True,  True,  True,  True,  True, False, False, False,
       False, False])

In [53]:
# 获取一个数组中非non的值
b = np.sqrt(a)
b[~np.isnan(b)]

/var/folders/hr/ppfykdg56ks4mjvczmbjkv1w0000gn/T/ipykernel_72453/3169532824.py:2: RuntimeWarning: invalid value encountered in sqrt
  b = np.sqrt(a)


array([0.70710678, 1.22474487, 1.58113883, 1.87082869, 2.12132034])

In [54]:
# inf
a = np.array([3,4,5,6,7])
b = np.array([3,0,5,0,7])
c = a / b

/var/folders/hr/ppfykdg56ks4mjvczmbjkv1w0000gn/T/ipykernel_72453/3310814698.py:4: RuntimeWarning: divide by zero encountered in true_divide
  c = a / b


In [55]:
# 获取数组中非inf的值
c[~np.isinf(c)]

array([1., 1., 1.])

### 二元函数

In [56]:
# 两个列表对比取最大值
a = np.array([3,4,5,6,7])
b = np.array([2,5,3,7,4])
np.maximum(a,b)

array([3, 5, 5, 7, 7])

## 统计方法

In [57]:
a = np.array([3,4,5,6,7])

In [58]:
# 求和
np.sum(a)

25

In [59]:
# 求平均数
np.mean(a)

5.0

In [60]:
# 求标准差
# 方差之后开根
np.std(a)

1.4142135623730951

In [61]:
# 求方差
# 每一个数减去均值算平方再求和
# 整组数据的离散程度
np.var(a)

2.0

In [62]:
# 最大数
np.max(a)
# 最小数
np.min(a)

3

In [63]:
# 最大数的下标
np.argmax(a)
# 最小数的下标
np.argmin(a)

0

## 随机数生成

In [64]:
# 随机数
# 起始值 最大值，元素个数
np.random.randint(0,6,10)

array([4, 1, 1, 3, 5, 3, 4, 5, 4, 2])

In [65]:
# 起始值 最大值，多维数组(行数，列数)
np.random.randint(0,6,(3,4))

array([[5, 3, 3, 4],
       [1, 1, 3, 0],
       [0, 1, 1, 1]])

In [66]:
# 0~1随机数
np.random.rand(5)

array([0.8601245 , 0.43094964, 0.76385725, 0.33855254, 0.06497139])

In [67]:
# 随机选择
# 数组，随机选择的次数
np.random.choice(np.arange(0,11),5)

array([0, 2, 2, 6, 7])

In [68]:
# 平均分布
# 起始值，结束值-1，次数
np.random.uniform(0,10,5)

array([2.18706634, 2.16589467, 2.03975439, 9.55936115, 9.01582069])