# numpy

In [69]:
import numpy as  np

### 创建多维数组对象
#### ndarray
```python
import numpy as  np
np.array('array_like')
```

##### 数组与列表区别
- 数组对象内的元素类型必须相同
- 数组大小不可修改
##### ndarray数据了性
- 布尔型 bool_
- 整型 int_ int8 int16 int32 int64
- 无符号整形 uint8 uint16 uint32 uint64
- 浮点型 float_ float16 float32 float64
- 复数型 complex_ complex64 complex128

In [70]:
import random
a = np.array([random.uniform(1,100) for i in range(100)])
b = np.array([random.randint(100,200) for i in range(100)])

In [71]:
# 数组元素同时运算
a * 2

array([ 97.33778688, 104.95125726,  66.84434743,  25.45863451,
       178.013702  , 174.36963822,  40.49228996,  31.51351867,
        44.40697   , 126.67758328, 153.38366529,  37.88030585,
       183.93821157,  87.4723386 ,   5.19577865, 130.08971031,
       194.96920768, 106.31265381,  12.44166956, 160.42208613,
       152.47575616, 196.44307409,  57.25151674,  75.60275531,
       120.36470275, 177.51093564,  31.72255188, 125.24884746,
        23.76235923, 152.67419073,  45.14083084, 137.13271379,
       131.92762391, 172.87392735, 141.66492635,  99.12396683,
       181.03263624,  35.98331912, 174.56631537,  91.85485367,
       141.40920956,  45.86127328, 154.24959784, 116.01338547,
        27.11177774, 110.04521034,  38.18628984, 146.94995574,
       175.30570966,  78.67995742, 178.74736112,  23.02613707,
        73.00900489, 120.25559599,  25.74516394,  62.03989456,
        66.15860743,  58.84077592,  19.25933426,  60.92124253,
        10.92540268,  69.60686948,  13.70424078,  56.41

In [72]:
# 两个数组运算
a * b

array([ 9052.41417996,  7136.6854937 ,  5180.43692609,  1998.50280867,
        9612.73990825, 11334.02648447,  3867.01369153,  1796.27056416,
        3552.55760006, 10704.255787  , 14724.83186827,  3030.42446814,
       16094.59351225,  7741.30196654,   493.59897201, 11382.84965212,
       14720.17517957,  8451.85597772,  1163.2961042 ,  9063.84786629,
        9453.49688213, 12474.13520454,  3606.84555475,  4536.16531844,
        7582.97627296, 12869.54283366,  1919.21438874,  6450.31564408,
        1592.07806812,  9465.799825  ,  2437.60486523,  8845.06003924,
       12401.19664799, 15126.46864282,  9562.38252844,  8574.22313045,
       15840.35567115,  2788.70723145, 12917.90733748,  5740.92835414,
        7282.57429211,  3485.45676908, 14113.83820243, 10557.21807821,
        2385.83644144,  7483.07430311,  1909.31449209, 14694.99557367,
       15514.5553049 ,  5900.99680686, 17070.37298697,  1715.44721178,
        5475.67536687, 10522.3646495 ,  1763.54373001,  5273.3910373 ,
      

In [73]:
# 两个数组同时运算并求和
(a * b).sum()

727304.3416179684

In [74]:
# 数组类型
a.dtype

dtype('float64')

In [75]:
# 数组元素个数
a.size

100

In [76]:
# 多维数组
a = np.array([[1,2,3],[4,5,6]])

In [77]:
# 多维数组类型
a.dtype

dtype('int64')

In [78]:
# 多维数组元素个数
a.size

6

In [79]:
# 多维数组纬度个数(行数，列数)
a.shape

(2, 3)

In [80]:
a = np.array([[1,2,3],[4,5,6],[7,8,9],[10,11,12]])
a

array([[ 1,  2,  3],
       [ 4,  5,  6],
       [ 7,  8,  9],
       [10, 11, 12]])

In [81]:
# 数组转置[[1,2,3],[4,5,6]]转换成[[1.4],[2,5],[3,6]]
a.T

array([[ 1,  4,  7, 10],
       [ 2,  5,  8, 11],
       [ 3,  6,  9, 12]])

In [82]:
# 返回数组纬度
a.ndim

2

## 创建数组

### 创建全零数组

In [83]:
# 创建浮点数数组
n = np.zeros(10)
n.dtype

dtype('float64')

In [84]:
# 创建整型数组
n = np.zeros(10, dtype='int_')
n.dtype

dtype('int64')

### 创建全一数组

In [85]:
n = np.ones(10)
n = np.ones(10,dtype='int_')
n.dtype
n

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1])

### 创建空数组（随机值）

In [86]:
n = np.empty(100)
n

array([48.66889344, 52.47562863, 33.42217372, 12.72931725, 89.006851  ,
       87.18481911, 20.24614498, 15.75675933, 22.203485  , 63.33879164,
       76.69183265, 18.94015293, 91.96910578, 43.7361693 ,  2.59788933,
       65.04485515, 97.48460384, 53.1563269 ,  6.22083478, 80.21104306,
       76.23787808, 98.22153704, 28.62575837, 37.80137765, 60.18235137,
       88.75546782, 15.86127594, 62.62442373, 11.88117961, 76.33709536,
       22.57041542, 68.56635689, 65.96381196, 86.43696367, 70.83246317,
       49.56198341, 90.51631812, 17.99165956, 87.28315769, 45.92742683,
       70.70460478, 22.93063664, 77.12479892, 58.00669274, 13.55588887,
       55.02260517, 19.09314492, 73.47497787, 87.65285483, 39.33997871,
       89.37368056, 11.51306854, 36.50450245, 60.127798  , 12.87258197,
       31.01994728, 33.07930371, 29.42038796,  9.62966713, 30.46062126,
        5.46270134, 34.80343474,  6.85212039, 28.20534403, 43.69084253,
       55.98806081, 59.51398091, 80.99749835, 50.46710574, 23.55

### 创建数组类似于range

In [87]:
n = np.arange(0,100,2) # 起始值，结束值-1，步长(可以是小数)
n

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48, 50, 52, 54, 56, 58, 60, 62, 64, 66,
       68, 70, 72, 74, 76, 78, 80, 82, 84, 86, 88, 90, 92, 94, 96, 98])

### 等差数列数组

In [88]:
n = np.linspace(0,100,1000) # 起始值 结束值 拆分份数
n

array([  0.        ,   0.1001001 ,   0.2002002 ,   0.3003003 ,
         0.4004004 ,   0.5005005 ,   0.6006006 ,   0.7007007 ,
         0.8008008 ,   0.9009009 ,   1.001001  ,   1.1011011 ,
         1.2012012 ,   1.3013013 ,   1.4014014 ,   1.5015015 ,
         1.6016016 ,   1.7017017 ,   1.8018018 ,   1.9019019 ,
         2.002002  ,   2.1021021 ,   2.2022022 ,   2.3023023 ,
         2.4024024 ,   2.5025025 ,   2.6026026 ,   2.7027027 ,
         2.8028028 ,   2.9029029 ,   3.003003  ,   3.1031031 ,
         3.2032032 ,   3.3033033 ,   3.4034034 ,   3.5035035 ,
         3.6036036 ,   3.7037037 ,   3.8038038 ,   3.9039039 ,
         4.004004  ,   4.1041041 ,   4.2042042 ,   4.3043043 ,
         4.4044044 ,   4.5045045 ,   4.6046046 ,   4.7047047 ,
         4.8048048 ,   4.9049049 ,   5.00500501,   5.10510511,
         5.20520521,   5.30530531,   5.40540541,   5.50550551,
         5.60560561,   5.70570571,   5.80580581,   5.90590591,
         6.00600601,   6.10610611,   6.20620621,   6.30

### 线性代数，单位矩阵数组

In [89]:
n = np.eye(10) # 二维数组开始和最后的值相等
n

array([[1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 1., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 1., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.]])

### 批量运算

> 数组和标量之间的运算
> a+3 a*3 1//a a**0.5 a>5
> 同样大小数组之间的运算
> a+b a/b a**b a%b a==b

标量：一个定义好的数字
向量：一个定义好的数组

In [90]:
# 数组和标量之间的运算
# a+3 a*3 1//a a**0.5 a>5
a = np.arange(10)
a + 1

array([ 1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [91]:
# 同样大小数组之间的运算
# a+b a/b a**b a%b a==b
a = np.arange(1,10)
b = np.arange(7,16)
a < b

array([ True,  True,  True,  True,  True,  True,  True,  True,  True])

#### 生成二维数组

In [92]:
n = np.arange(15).reshape((3,5))
n

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

#### 索引

In [93]:
n[1][2]
# 第二种写法
n[1,2]

7

#### 切片

In [94]:
n = np.arange(15)

In [95]:
n[0:4]

array([0, 1, 2, 3])

##### 数组与列表 切片中的不同

> 数组是内存地址引用，列表是映射

In [96]:
a = [0,1,2,3,4,5,6,7,8,9]
b = np.arange(10)
c = a[0:4]
d= b[0:4]
c[0] = 20
d[0] = 20

In [97]:
a # python 列表 切片 数据映射 会生成新的列表，原列表值不会改变

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]

In [98]:
b
# 数组 切片 地址引用 不会生成新的列表 在原有列表做地址引用 切片赋值会改变原数组值
# 如果想达到列表的效果可以在切片赋值前将切片的数据b.copy() 深拷贝生成一个新数组

array([20,  1,  2,  3,  4,  5,  6,  7,  8,  9])

#### 多维数组切片

In [99]:
# 数据准备
a = np.arange(15).reshape(3,5)
a

array([[ 0,  1,  2,  3,  4],
       [ 5,  6,  7,  8,  9],
       [10, 11, 12, 13, 14]])

In [100]:
# 多维数组切片  a[行:行-1,列:列-1]
a[1:,2:4]

array([[ 7,  8],
       [12, 13]])

### 布尔型索引

In [101]:
# 给一个数组选出元素大于5的数
a = [random.randint(0,10) for i in range(10)]
list(filter(lambda x:x>5,a))

[7, 7]

In [102]:
# numpy 实现方法
a = np.array(a)
# 返回所有布尔索引为true的值
a[a>5]

array([7, 7])

In [103]:
# 与 或
a[(a>5)&(a%2==0)]

array([], dtype=int64)

In [104]:
a[(a>5) | (a%2==0)]

array([0, 7, 7, 0, 4, 2, 2])

### 花式索引(没懂)

In [105]:
# 选出1，3，4，6，7个数组，组成新的二维数组

In [106]:
a = np.arange(20)
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [107]:
a[[1,3,4,6,12]]

array([ 1,  3,  4,  6, 12])

## 通用函数
> 能同时对数组中所有元素进行运算的函数
一元函数：abs,sqrt,exp,log,ceil,floor,rint,trunc,modf,isnan,isinf,cos,sin,tan
二元函数：add,substract,multiply,divide,power,mod,maximum,mininum

### 一元函数

In [108]:
# 绝对值
a = np.arange(-5,5)
np.abs(a)

array([5, 4, 3, 2, 1, 0, 1, 2, 3, 4])

In [109]:
# 开方

In [110]:
a = np.arange(5,10)
np.sqrt(a)

array([2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

In [111]:
# 按方向取整

In [112]:
a = np.arange(-5.5, 5.5)
a

array([-5.5, -4.5, -3.5, -2.5, -1.5, -0.5,  0.5,  1.5,  2.5,  3.5,  4.5])

In [113]:
# 向下取整
np.floor(a)

array([-6., -5., -4., -3., -2., -1.,  0.,  1.,  2.,  3.,  4.])

In [114]:
# 向下取整
np.ceil(a)

array([-5., -4., -3., -2., -1., -0.,  1.,  2.,  3.,  4.,  5.])

In [115]:
# 四舍六入五成双
np.round(a)

array([-6., -4., -4., -2., -2., -0.,  0.,  2.,  2.,  4.,  4.])

In [116]:
# 向零取整
np.trunc(a)

array([-5., -4., -3., -2., -1., -0.,  0.,  1.,  2.,  3.,  4.])

In [117]:
# 把小数分开
np.modf(a)

(array([-0.5, -0.5, -0.5, -0.5, -0.5, -0.5,  0.5,  0.5,  0.5,  0.5,  0.5]),
 array([-5., -4., -3., -2., -1., -0.,  0.,  1.,  2.,  3.,  4.]))

### 浮点数特殊值
> nan：不等于任何浮点数（nan ！= nan）(不是一个数字)   特性：nan ！= nan
inf：比任何浮点数都大（最大的数字）   特性:inf == inf
np创建特殊值：np.nan   np.inf
在数据分析中，nan常被用作数据缺失值

In [118]:
#
a = np.arange(0, 5)
5/a

/var/folders/hr/ppfykdg56ks4mjvczmbjkv1w0000gn/T/ipykernel_72453/924957107.py:3: RuntimeWarning: divide by zero encountered in true_divide
  5/a


array([       inf, 5.        , 2.5       , 1.66666667, 1.25      ])

In [119]:
a = np.arange(-5.5,5.5)
np.sqrt(a)

/var/folders/hr/ppfykdg56ks4mjvczmbjkv1w0000gn/T/ipykernel_72453/2623976932.py:2: RuntimeWarning: invalid value encountered in sqrt
  np.sqrt(a)


array([       nan,        nan,        nan,        nan,        nan,
              nan, 0.70710678, 1.22474487, 1.58113883, 1.87082869,
       2.12132034])

In [120]:
# 判断数组里是否有nan值
np.isnan(np.sqrt(a))

/var/folders/hr/ppfykdg56ks4mjvczmbjkv1w0000gn/T/ipykernel_72453/1843299488.py:2: RuntimeWarning: invalid value encountered in sqrt
  np.isnan(np.sqrt(a))


array([ True,  True,  True,  True,  True,  True, False, False, False,
       False, False])

In [121]:
# 获取一个数组中非non的值
b = np.sqrt(a)
b[~np.isnan(b)]

/var/folders/hr/ppfykdg56ks4mjvczmbjkv1w0000gn/T/ipykernel_72453/3169532824.py:2: RuntimeWarning: invalid value encountered in sqrt
  b = np.sqrt(a)


array([0.70710678, 1.22474487, 1.58113883, 1.87082869, 2.12132034])

In [122]:
# inf
a = np.array([3,4,5,6,7])
b = np.array([3,0,5,0,7])
c = a / b

/var/folders/hr/ppfykdg56ks4mjvczmbjkv1w0000gn/T/ipykernel_72453/3310814698.py:4: RuntimeWarning: divide by zero encountered in true_divide
  c = a / b


In [123]:
# 获取数组中非inf的值
c[~np.isinf(c)]

array([1., 1., 1.])

### 二元函数

In [124]:
# 两个列表对比取最大值
a = np.array([3,4,5,6,7])
b = np.array([2,5,3,7,4])
np.maximum(a,b)

array([3, 5, 5, 7, 7])

## 统计方法

In [125]:
a = np.array([3,4,5,6,7])

In [126]:
# 求和
np.sum(a)

25

In [127]:
# 求平均数
np.mean(a)

5.0

In [128]:
# 求标准差
# 方差之后开根
np.std(a)

1.4142135623730951

In [129]:
# 求方差
# 每一个数减去均值算平方再求和
# 整组数据的离散程度
np.var(a)

2.0

In [130]:
# 最大数
np.max(a)
# 最小数
np.min(a)

3

In [131]:
# 最大数的下标
np.argmax(a)
# 最小数的下标
np.argmin(a)

0

## 随机数生成

In [132]:
# 随机数
# 起始值 最大值，元素个数
np.random.randint(0,6,10)

array([0, 3, 2, 4, 5, 2, 3, 0, 1, 5])

In [133]:
# 起始值 最大值，多维数组(行数，列数)
np.random.randint(0,6,(3,4))

array([[5, 2, 1, 4],
       [1, 0, 1, 3],
       [1, 0, 0, 0]])

In [134]:
# 0~1随机数
np.random.rand(5)

array([0.5617229 , 0.30080745, 0.77202457, 0.29916952, 0.03758809])

In [135]:
# 随机选择
# 数组，随机选择的次数
np.random.choice(np.arange(0,11),5)

array([3, 1, 4, 2, 8])

In [136]:
# 平均分布
# 起始值，结束值-1，次数
np.random.uniform(0,10,5)

array([0.67820206, 9.9411374 , 3.23584091, 5.28454914, 3.10371172])